name: golfpose
channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pillow
  - opencv
  - hdf5

  - pip:
      - torch==1.12.1
      - torchvision==0.13.1
      - torchaudio==0.12.1
      - absl-py
      - addict
      - aiohttp==3.6.2
      - attrs
      - chumpy
      - einops
      - fsspec
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - huggingface-hub
      - json-tricks
      - local-attention
      - markdown
      - matplotlib-inline
      - mdurl
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.3
      - mmpose==1.3.1
      - model-index
      - openmim
      - ordered-set
      - pastedeploy
      - protobuf
      - pycocotools
      - pyyaml
      - requests
      - rich
      - safetensors
      - shapely
      - tensorboard
      - timm
      - tqdm
      - yapf
      - xtcocotools